name: Java CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./gradlew
      - run: ./gradlew build
